### PR TITLE
Storybook a11y

### LINKED ISSUE #927: Storybook a11y
We need to inject `is_a11y_mode` into storybook to test components in their a11y states.. So we may need different ways other than DefinePlugin to inject build constants..

### PR DESCRIPTION
**Pull request by GarvinH**
closes #927 

Didn't manage to find a better way to do this, but yet I still feel like there has to be a better way to handle this...

### CODE REVIEW

**Comment by ktw1016** [comment]
Hmmm yeah I was playing around with this one too and couldn't find a good solution. Honestly, I think it could just be having two separate commands like `storybook` and `storybook-a11y`.. We would also need to do that for the dev link of the storybook

**Comment by ktw1016** [comment]
Was the a11y injected variable working locally? I don't see a11y version of the dev link changed

**Comment by GarvinH** [comment]
Yea it was working locally. I think none of the current stories contain any components that appear differently on the a11y versions.

I'll go ahead and find a component which has a11y and see if it works on dev link

**Comment by GarvinH** [comment]
Typo in the package.json 😂🤦‍♂️. Gonna double check and push

**Comment by GarvinH** [comment]
Okay it should be good now!

**Review by ktw1016 — APPROVED** [review]
I'm good with this but let's see what others think of this

**Review by Stephen-ONeil — APPROVED** [review]
Hmm, thought through it a bit more. Since we set our constants at build time and import them from a module, this is only addressable as a webpack/build time problem, duh. We'd have to change how `injected_build_constants.js` works to be able to mock it. We'll need a good solution to that to that eventually for unit testing, and it should be something storybook could share, but this is the only incremental solution we have for now.

**Comment by Stephen-ONeil** [comment]
@GarvinH If you merge this and close the current issue, open a new issue about the general handling of the build time constants. We want to (in dev mode only probably) be able to override them. Reference back to the original storybook issue since we'll want to revisit this solution once that exists.

**Pull request merged**
