### PR TITLE
Update nivo

### PR DESCRIPTION
**Pull request by Stephen-ONeil**
Going to need a lot of eyes on this dev build (once it's ready) to look for chart errors. I'll do the IE testing.

### CODE REVIEW

**Comment by Stephen-ONeil** [comment]
Hmm, package patches didn't get applied in CI?

**Comment by Stephen-ONeil** [comment]
TODOs:
  - [ ] fix patch-package in CI
  - [ ] GOCO graph hover fading the wrong bars
  - [ ] replace legends with our own
  - [ ] sort items in line slice tooltips 
  - [ ] Spending by Standard Objects line graph colours

**Comment by ktw1016** [comment]
- [ ] Color issue: http://dev.ea-ad.ca/update-nivo/index-eng.html#orgs/dept/1/infograph/financial/.-.-(panel_key.-.-'spend_by_so_hist)

- [x] No data points (I think I know this one, I can fix it): http://dev.ea-ad.ca/update-nivo/index-eng.html#orgs/dept/146/infograph/financial/.-.-(panel_key.-.-'auth_exp_prog_spending)

**Comment by ktw1016** [comment]
So there's still an error in goco on spending area text opacity when you click on the graph.. It should be faded out but it doesn't. (It actually does fade out in `handleClick`, but I think something else gets triggered after to set unfade it. and I can't figure that out)

**Comment by Stephen-ONeil** [comment]
Low priority, putting on-hold to focus on bugstravaganza.

**Comment by Stephen-ONeil** [comment]
There are so many little unfixable (without going full hack, and I can't get in to the habit of hitting every nail with the `patch-package` hammer) headaches here, I'm going to drop this PR. 

New plan is to wait for nivo to _**actually stabilize**_ (or at least have a new feature worth the update pain) before updating it again. Not worth going through this more than once. Risk that it ends up meaning our current code is too far out of sync to simply update, but in that case we can just do a full re-write of everything using nivo and probably come out the better for it.

**Comment by ktw1016** [comment]
rip nivo😱

**Comment by Stephen-ONeil** [comment]
😞

**Pull request closed without merging**
