### PR TITLE
Drop legacy routes, home page cleanup

### PR DESCRIPTION
**Pull request by Stephen-ONeil**
Temporarily a branch off of `break-up-d3-bundle`. They were originally happening together so the commit messages might look extra scattered on both, ha.

Drop the lab route, lift the text diff to the home page. Drop the treemap and partition diagram.

Redesign/reorg and refactor of home page.

### CODE REVIEW

**Comment by Stephen-ONeil** [comment]
... dropping the partition diagram might be back off the table. Treemap is still questionable. Even if both stay though, the lab should go and the home page refactor (once finished) is still needed.

**Comment by AlexCLeduc** [comment]
I thought we were keeping the treemap since it offers things not available anywhere else, like visually-scaled diffing of $/FTEs?

For the partition, can a student try to generalize the partition and put it in a storybook, or a separate repo? We can move forward with removing links to the partition, but keep it alive while a student extracts it.

**Comment by Stephen-ONeil** [comment]
> I thought we were keeping the treemap since it offers things not available anywhere else, like visually-scaled diffing of $/FTEs?

I've been swayed by that argument a couple times, but then I look at the analytics and remember it got less than 25 visits in the last year. It's unique functionality... that seemingly no one knows is there.  

> For the partition, can a student try to generalize the partition and put it in a storybook, or a separate repo? We can move forward with removing links to the partition, but keep it alive while a student extracts it.

In both cases, I intend to archive them with a permanent dev link, but neither are worth the time investment IMO. They're fancy nice-to-haves, but get no traffic in comparison to the Infographics/home page/report builder. I'd rather improve infographic navigation and panel content, the home page's search functionality, and the report builders general usability. The bonus sub-apps can wait.

**Comment by ktw1016** [comment]
I like the new home layout, it'd be easier to extend the bubbles here for sure.

Removing treemap and partition should definitely make big migrations easier like typescript, or full GraphQL migration. But I'm neutral on removing them because I think there are some values in keeping them around. (it demos well, easier to promote InfoBase with them).  I'm against archiving partition diagram though. Once we archive that, I highly doubt it'll ever see a light in the day again. Not worth the time of archiving or trying to work on it at that point so better to just fully remove it IMO

**Comment by Stephen-ONeil** [comment]
Archived Links:
  - [Treemap](http://dev.ea-ad.ca/archived__partition_and_treemap/index-eng.html#treemap)
  - [Partition](http://dev.ea-ad.ca/archived__partition_and_treemap/index-eng.html#partition)

**Pull request merged**
