### PR TITLE
Round off square bubbles

### LINKED ISSUE #378: rounded off edges
Screen Shot 2019-11-25 at 2 45 29 PM

Not too sure how important it is, but it seems like bubbles are the only 90 degree edges

### PR DESCRIPTION
**Pull request by Stephen-ONeil**
Closes #378 

I think the rounded bubble menu might even be a bit of an improvement.

TODO:
  - [x] look through `border-radius` values throughout app, see how many of them can, reasonably, be standardized to 10px/the Sass var
    - Some of that may have been unnecessary?

### CODE REVIEW

**Comment by Stephen-ONeil** [comment]
I forget why this isn't currently marked `awaiting review`, not sure what my remaining TODOs were. Had we talked about making all buttons square or something out-there like that? May have just been because it was contentious change and something I wanted wider feedback on.

**Comment by Stephen-ONeil** [comment]
Ok, I'm marking this `awaiting review` primarily for the border-radius standardization. If all of that feels reasonable, I'll re-round the bubble menu items and merge this in (so the standardization work doesn't get lost while we weigh the style change).

**Comment by cookkate** [comment]
Last I looked at this it was the style discussion that was still outstanding. I'll take a look at the rest of the changes in the mean time.

I guess we should make another PR that makes the actual change so that we have something to debate? Or did you want to just send around screenshots?

**Comment by Stephen-ONeil** [comment]
Hmm. To my eyes, fresh from the holidays, the rounded bubble menu items are an improvement. I'm going to break with what I said I'd do and merge this with the bubbles rounded. If it's hated we can roll it back very easily, and it's such a small change that I don't care if that roll-back happens after it's gone in to prod.

**Pull request merged**
