### PR TITLE
collapsed panels

### LINKED ISSUE #401: Stay-collapsed panels?
Would be nice if users could collapse panels they're not interested in and leave them closed. Would help make the longer infographics (e.g. dept financial) a little more useful.

### PR DESCRIPTION
**Pull request by ktw1016**
fixes #401 

Just first initial to let everyone check it out

### CODE REVIEW

**Comment by cookkate** [comment]
Code looks fine. Comment about functionality though--you should hide the buttons at the top right, both because it doesn't make sense to have them functional and because the PDF download button errors if you click it on a closed panel :)

**Comment by ktw1016** [comment]
Ohh yup true!

**Comment by cookkate** [comment]
Also this is nitpicky but can you align the triangle/arrow to the text? It looks like the text isn't centred vertically on the header but the triangle is.

**Comment by cookkate** [comment]
What's wrong with this applying to datasets panels? Panel is generic, but not that generic. It also has all the footer stuff like glossary keys and footnotes in it, which only apply to the infographics.

**Comment by ktw1016** [comment]
@Stephen-ONeil are there any reasons why datasets shouldn't be collapsed?

**Comment by Stephen-ONeil** [comment]
I thought the intention of this PR was just to add collapsing to infographic panels. It isn't necessarily a bad feature in either place but, in my books, if it isn't intentional then it is a bug.

I don't think it is necessary on the dataset page. Maybe useful on the text diff. Would still prefer it as a panel util for design purposes\*. Like I said though, I can be out-voted on this for now if y'all want to rush in to production. 

\* design thoughts:
  - all the other general panel interactivity is grouped on the right, introducing something elsewhere breaks that convention. I'd prefer not to
  - I know it is supposed to invoke a details drawer but, overall, I don't think it looks enough like our other details drawers to pull that off. The arrow before the title might just look like an attempt at a stylistic bullet point?

@cookkate good point, leaving footnotes and glossary items in the  general Panel component was a mistake :p

**Comment by ktw1016** [comment]
Yup no problem, I'll merge this in for now then!

**Pull request merged**
