### PR TITLE
Axe core

### LINKED ISSUE #798: Look into axe core
We can add this in to our CI that automatically checks some a11y stuff, think this one would be pretty useful

https://github.com/dequelabs/axe-core

### PR DESCRIPTION
**Pull request by ktw1016**
closes #798 

https://github.com/dequelabs/axe-cli

### CODE REVIEW

**Comment by ktw1016** [comment]
Waiting on #815 because current Typeahead will always throw errors

**Comment by ktw1016** [comment]
Hmmm HeightClipper with tabbable elements inside are not reached to change `tabIndex`. Might have to reach all elements recursively to reach all great grand children

**Comment by ktw1016** [comment]
Error documented and opened an issue here: https://github.com/dequelabs/axe-core-npm/issues/203

**Comment by Stephen-ONeil** [comment]
Paused or dead, pending dequelabs/axe-core-npm#203?

**Comment by ktw1016** [comment]
It seems like they might actually look into it, since they just added labels on my issue.. I'd like to wait a little longer and see their response

**Pull request closed without merging**
