### PR TITLE
Prettier! 

### PR DESCRIPTION
**Pull request by AlexCLeduc**
supports #597

you'll want to add this in your _workspace_ settings (`infobase/.vscode/settings.json`) 

```json
{
    "editor.formatOnSave": true
}
```

 and install the prettier extension in vscode: `esbenp.prettier-vscode`

### CODE REVIEW

**Comment by AlexCLeduc** [comment]
Tested CI, it works. [Here's a passing commit](https://github.com/TBS-EACPD/infobase/commit/2fa7bcc39feff078339708bd06b249be1712a356) with all files formatted.


I added the check in CI and made it fail right before tests are run. I think it's worth it to check formatting in CI, because it'll break more often than we think.
It made the `test_server` and `test email_backend` step a little bit longer, but not by much. The `test_end_to_end` step's duration is too volatile for the `client/` format check addition to really matter.

a couple notes

- checking `email_backend/` is part of `test_email_backend`
- checking `server/` is part of `test_server`
- checking `client/` is part of `test_end_to_end`
- ignore rules are all in the top-level `.prettierignore` , maybe we should distribute these accross the app like we do with eslint, but we'd need a top-level one anyway 🤷

**Comment by Stephen-ONeil** [comment]
TODO:
  - [ ] read the docs my self, should try and tweak any rules I might want to before going through the work of getting this on all the open branches
  - [ ] https://prettier.io/docs/en/options.html#arrow-function-parentheses

**Comment by AlexCLeduc** [comment]
actually, since we're only formatting JS, you may want to use 

```
  "[javascript]": {
    "editor.formatOnSave": true
  }

```

instead of top-level  

```
"editor.formatOnSave": true
```

This just screwed me over in the python project when prettier formatted a yaml file and gave me an unexpectedly huge diff (And I forgot to use workspace settings)

**Comment by Stephen-ONeil** [comment]
> This just screwed me over in the python project when prettier formatted a yaml file and gave me an unexpectedly huge diff (And I forgot to use workspace settings)

I'm going to drop .vscode from the root level .gitignore and commit up the appropriate, JS only, `editor.formatOnSave` rule. One less manual dev env set up task, and will save everyone the sort of headache you got from putting it in their global settings.

**Pull request merged**
