### PR TITLE
Add docs on adding tmux config file

### PR DESCRIPTION
**Pull request by GarvinH**

### CODE REVIEW

**Comment by ktw1016** [comment]
This is actually in the docs! Take a look at step 3

**Comment by GarvinH** [comment]
😂🤦‍♂️

I did a search on `.tmux.conf` and didn't find anything. I can't believe i didn't see it when it was right in front of me

**Comment by GarvinH** [comment]
good catch! thanks

**Comment by ktw1016** [comment]
😂

**Pull request closed without merging**
