### PR TITLE
short survey submitted action is being over submitted, although googl…

### PR DESCRIPTION
**Pull request by ktw1016**
The actual code and google analytics report is contradicting each other:
- Code is over-logging "short_survey_submitted"
- Google Analytics only logged "short_survey_submitted" 9 times, even though it should've logged it at least hundred times

### CODE REVIEW

**Comment by ktw1016** [comment]
I don't think this solves the problem, but not sure how Google Analytic is under-logging "short_survey_submitted" and would be nice if someone can look it over

**Comment by Stephen-ONeil** [comment]
Don't have any immediate thoughts. If you're fully stuck, please document what you've tried back in the original issue and close this PR for now.

**Comment by ktw1016** [comment]
Don't have much to comment on it. We would need to find out the cause of google analytics under logging the short survey submitted first.

**Comment by ktw1016** [comment]
related #865

**Pull request closed without merging**
