### PR TITLE
Long (relative) to absolute imports

### PR DESCRIPTION
**Pull request by ChetanMandur**
related #868 

The rule I followed is that if the import isn't 'local', it becomes an absolute import.

### CODE REVIEW

**Comment by ktw1016** [comment]
I just had a quick look over and this is great! Do you wanna try adding the eslint rule that Alex linked in the issue? and this PR can close the issue

**Review by ktw1016 — APPROVED** [review]
🎉👍

**Comment by Stephen-ONeil** [comment]
One real minor thought, if you want to move this along it could be a follow up issue/PR, but I'm seeing imports like, e.g., `/components`, `/components/`, and `/components/index.js`. My preference is to always explicitly import the `index.js` in any case (for one thing, I believe the auto-ordering rule will treat it differently if it knows it's a JS file).

**Comment by Stephen-ONeil** [comment]
One other note, this could close the related issue if you want, just need to open a follow up issue about breaking up the legacy re-exporting files like `client/src/panels/panel_declarations/shared.js`.

**Comment by ChetanMandur** [comment]
I think breaking up legacy re-export files should be another PR. I'll make another issue once this PR gets merged.

Also, as a side note, does anyone know why the rebase and merge is causing conflicts?

**Comment by Stephen-ONeil** [comment]
> I think breaking up legacy re-export files should be another PR. I'll make another issue once this PR gets merged.

Sounds good to me!

> Also, as a side note, does anyone know why the rebase and merge is causing conflicts?

Haha, it's a little quirk of the GitHub UI. GitHub isn't showing you as having conflicts with master because you have merge commits resolving those conflicts already. A rebase operation doesn't apply merge commits though! So the tricky bit is that GitHub both tells you there are no conflicts (because of the resolutions in the merge commits) but also says you can't rebase automatically because of conflicts (true, but in that case, when the rebase option is selected, they should ignore the merge commits and just tell you where the conflicts are, IMO!).

Anyway, you can either change the dropdown from "Rebase and merge" to "Create a merge commit" on GitHub, or you can rebase off master on your local branch and re-fix the merge conflicts as they arise in the process, the force-push that version of the branch back up to here. Only bother with the local rebase if the merge conflicts weren't too bad.

Either way, in the future, whenever you want to reconcile with upstream changes, please use `git rebase master`, etc, instead of creating merge commits. Just because we've decided to stick with rebasing over merging on this project. It'll keep things more straightforward.

**Review by Stephen-ONeil — APPROVED** [review]
👍  🎉 

Awesome! See my early comment on the rebase vs merge question.

**Pull request merged**
