### PR TITLE
remove "narrowSymbol" from intl.NumberFormat as it was breaking speci…

### PR DESCRIPTION
**Pull request by ktw1016**
…fic safari versions

### CODE REVIEW

**Comment by Stephen-ONeil** [comment]
For additional context, `currencyDisplay: "narrowSymbol",` was added in #1069 due to an unwanted cross-browser addition of currency symbols in French dollar formats.

Safari seems to have generally broken `Intl.NumberFormat` support between 14.0 and 14.1.0 ([here's a different instance of it](https://community.atlassian.com/t5/Trello-questions/Trello-stuck-at-loading-after-Safari-14-1-update-on-macOS-Mojave/qaq-p/1675577#M45687)). Works before 14.0 and seems fixed as of 14.1.1.

(that seems contradicted by this, maybe more research is needed, but it at least didn't cause a hard crash pre-14
image
)

**Comment by Stephen-ONeil** [comment]
Ah, just double checked, this was broken in IE11 too, ha. Totally missed that when I added it.

**Comment by Stephen-ONeil** [comment]
From my PC (was testing IE), haven't checked other chromes yet.
image

**Comment by ktw1016** [comment]
Yeah just checked on IE on my personal desktop, mine is formatted correctly consistent with other browsers. No CA at the end

**Comment by Stephen-ONeil** [comment]
Sorry, meant to clarify that I was on my PC testing IE, but also checked chrome on windows which is where I took that screenshot. I haven't tested chrome on my other devices, but expect it is the same.

**Pull request closed without merging**
